name: molpay_mobile_xdk_flutter_beta
description: MOLPay mobile payment for Flutter (BETA)
version: 0.18.0
author: MOLPay Mobile Division
homepage: https://github.com/MOLPay/molpay-mobile-xdk-flutter-beta

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.molpay.molpaymobilexdkflutterbeta
    pluginClass: MolpayMobileXdkFlutterBetaPlugin